# Nombre del workflow
name: AI Security Code Review

# Cuándo se debe ejecutar
on:
  push:
    branches:
      - main
  pull_request:
    # Ahora nos enfocamos en los PRs
    types: [opened, synchronize] # Se ejecuta al abrir o actualizar un PR

# Permisos: ¡NUEVO Y CRÍTICO!
# Le da permiso al workflow para escribir en Pull Requests
permissions:
  pull-requests: write

jobs:
  ai-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run AI Security Analysis
        run: python scripts/analyze_code.py
        env:
          # El secreto de Anthropic, como antes
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          
          # ¡NUEVO! Pasa el token de GitHub al script
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          # ¡NUEVO! Pasa el número del PR al script
          # Esto solo existe si el evento es un 'pull_request'
          PR_NUMBER: ${{ github.event.pull_request.number }}
          
          # ¡NUEVO! Pasa la URL de la API
          GITHUB_API_URL: ${{ env.GITHUB_API_URL }}
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
