# Nombre del workflow
name: AI Security Code Review

# Cuándo se debe ejecutar
on:
  push:
    branches:
      - main  # Se ejecuta en cada push a la rama main
  pull_request:
    branches:
      - main  # También en pull requests a main

# Qué trabajos (jobs) debe ejecutar
jobs:
  ai-security-scan:
    # La máquina virtual que usará GitHub (Ubuntu es estándar y rápido)
    runs-on: ubuntu-latest

    steps:
      # Paso 1: "Clonar" tu código del repo a la máquina virtual
      - name: Check out repository
        uses: actions/checkout@v4

      # Paso 2: Configurar Python (para que 'pip' y 'python' funcionen)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Puedes usar la versión que prefieras

      # Paso 3: Instalar las dependencias de nuestro script
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Paso 4: Ejecutar nuestro script de análisis de IA
      - name: Run AI Security Analysis
        run: python scripts/analyze_code.py
        env:
          # ¡Aquí está la magia! 
          # Pasa el secreto de GitHub como una variable de entorno
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

